### ISSUE TITLE
Licensed to use?

### ISSUE THREAD

**Issue by gyehuda** [acesinc/druid-cors-filter-extension#1]
Andrew, can you add a license to this repo? We'd love to use this code and get the benefit from it, but without an explicit license we can only read this code, but not actually use it. (True, that's the law.)

Since Druid itself is Apache licensed, that would make the most sense to use since the community of Druid users already likes it. But it's up to you if you want to use something else instead. http://choosealicense.com/ for details.

Please add a LICENSE file to the repo (you can update the readme and the code file headers if you wish, or not, up to you). Once that's there, the community can use your code and thank you for it.

**Comment by andrewserff** [comment]
I just added the Apache License v2.0. Thanks for pointing that out! We've got it in other open source projects, but this was one of our firsts, so must have missed it. Happy Coding!
